#version: '3'

services:

  back:
    build:
      context: ./app/back
      target: development-stage
    labels:
      - traefik.enable=true
      - traefik.http.routers.back_router.rule=${BACK_ROUTER_RULE}
      - traefik.http.routers.back_router.service=back_service
      - traefik.http.services.back_service.loadbalancer.server.port=3000
    volumes:
      - ./app/back:/var/www/html
    depends_on:
      - postgres

  front:
    build:
      context: ./app/front/
      target: development-stage
    labels:
      - traefik.enable=true
      - traefik.http.routers.front_router.rule=${FRONT_ROUTER_RULE}
      - traefik.http.routers.front_router.service=front_service
      - traefik.http.services.front_service.loadbalancer.server.port=3000
    volumes:
      - ./app/front:/var/www/html

  reverse-proxy:
    image: traefik:3.0
    command:
      --api.insecure=true
      --providers.docker
    labels:
      - traefik.enable=false
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data

volumes:
  docker-nest-postgres: