#version: '3'

services:

  api:
    build:
      context: ./app/back/
    ports:
      - "80:3000"

  app:
    build:
      context: ./app/front/
    ports:
      - "3000:3000"


  # api:
  #   build:
  #     context: ./app/back/
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.api.rule=${BACK_ROUTER_RULE}
  #     - traefik.http.services.api.loadbalancer.server.port=80

  # app:
  #   build:
  #     context: ./app/front/
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.app.rule=${FRONT_ROUTER_RULE}
  #     - traefik.http.services.api.loadbalancer.server.port=3000

  # reverse-proxy:
  #   image: traefik:3.0
  #   command:
  #     --api.insecure=true
  #     --providers.docker
  #   labels:
  #     - traefik.enable=false
  #   ports:
  #     - "80:80"
  #     - "8080:8080"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

